name: Update LLM Prices

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggers
  push:
    branches:
      - master

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Check for updates and commit if needed
        run: |
          python .github/scripts/update_prices.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 